### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by achmadk** [goto-bus-stop/react-bus#7]
hello, @goto-bus-stop . Thanks for creating this awesome library, `react-bus`. I want to use it into my web app written in typescript language. Unfortunately I can't find typescript definition of this library. Can I help you to create that one?

**Comment by achmadk** [comment]
if you don't mind, please check [this link](https://github.com/goto-bus-stop/react-bus/compare/default...achmadk:typescript-support) to solve this issue.

**Comment by goto-bus-stop** [comment]
@achmadk would you like to submit a PR with those changes?
